### ISSUE TITLE
Firefox is not switching between light/dark

### ISSUE THREAD

**Issue by cmnstmntmn** [pacocoursey/next-themes#40] opened 2021-04-07 08:27 UTC
Hei,

First of all i want to thank you about this lib ;)
I have an issue with Firefox, even if the local storage is set and the class is added on 
`<html>`the theme does not change.

I'm using the last next.js with **tailwind jit**

**Comment by christofferberg** [comment] 2021-04-07 14:19
I haven't looked in depth, but it seems like there's an issue in version `0.0.14`. Try downgrading to `0.0.10`.

**Comment by trm217** [comment] 2021-04-07 15:49
I tested this with V 0.0.14 in my Next.js deployment. It works as expected with no issues.
However unlike you, I don't use the JIT compiler, perhaps it has something to do with that.
Either way I doubt the problem is related to this package. I suppose it's a Tailwind error, have you checked if the compiled output is as expected?

**Comment by pacocoursey** [comment] 2021-04-07 16:14
Hey, I was able to reproduce this issue. I'll take a look today

**Comment by trm217** [comment] 2021-04-07 16:16
> Hey, I was able to reproduce this issue when the theme is `system`. I'll take a look today

That's odd, how exactly could you reproduce it? On what OS are you working on?

**Comment by pacocoursey** [comment] 2021-04-07 16:34
My mistake – could not actually reproduce! Using `next@latest` with `tailwindcss@latest`, including `mode: jit`.

@christofferberg You mentioned there may be some issues in 0.0.14, could you provide a reproduction?

**Comment by jhg023** [comment] 2021-04-23 17:16
I had a similar issue, and I was able to fix it by setting `enableColorScheme={false}` in the `<ThemeProvider>`.

**Comment by pacocoursey** [comment] 2021-04-23 18:04
Do you have any more details @jhg023? Things like `defaultTheme`, what was in localStorage, and what the current theme was would be helpful. And a reproduction would be best of all 👑

**Comment by jhg023** [comment] 2021-04-23 18:15
@pacocoursey I'm happy to help, but frontend development isn't my area of expertise, so you'll have to bear with me.

My provider was initially defined as `<ThemeProvider attribute="class" defaultTheme="dark">`, and the library it was conflicting with was `react-use-intercom` (https://www.npmjs.com/package/react-use-intercom, version `1.1.9`).

The only relevant value in my local storage is `theme` mapped to a value of `dark`, which is the same whether or not I set `enableColorScheme={false}`.

**Comment by Thisisjuke** [comment] 2021-05-04 09:34
Hello everyone, I had the same issue in my NextJS app, with TailwindCSS (without JIT). 
I might be wrong, but I fixed it on my project.

### CONTEXT 

Working great on chrome and Safari : I can switch between themes. 
When switching on Firefox, only my TailwindCSS classes prefixed by `dark:` where working : no auto change of the text-color or background-color :disappointed: 

### WHY IS IT HAPPENING ?

Firefox seems to have few problems with [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), triggered with `enableColorScheme` props

The developer of a dark-theme Firefox extension said that some things are missing inside the browser API.
https://discourse.mozilla.org/t/how-to-test-preferred-color-scheme-dark-mode-with-firefox/40769/4

### HOW TO FIX IT ?

Sad to say, but if you are encountering this issue, you should do `enableColorScheme = false` and style all your DOM with custom Tailwind class : **Don't let the browser API do changes for you**
Add `dark:bg-dark dark:text-white` on your `<body>`

No magic here, a little more work on the text and the buttons, but you can fully use `next-themes` on all your browsers !
I hope it helped a bit !
Peace :v:

**Comment by pacocoursey** [comment] 2021-05-05 20:12
Thank you for the additional details and fix! I think I'll make `enableColorScheme` be `false` by default in a new version until all browsers can properly support it.

**Comment by trm217** [comment] 2021-05-05 20:31
@pacocoursey if it was true so far couldn‘t this break existing pages? I believe it would be better to add a disclaimer for firefox behavior but not change the behavior. Firefox is just on of many browsers and most are chromium based. So it should work as expected for most.

**Comment by pacocoursey** [comment] 2022-02-20 16:02
The latest few Firefox versions support `color-scheme` and I haven't been able to reproduce this for a while, closing. Please let me know if it's still an issue!

**Closed by pacocoursey** 2022-02-20 16:02 UTC
Labels: bug
