### ISSUE TITLE
Theme flashing 

### ISSUE THREAD

**Issue by gr-qft** [pacocoursey/next-themes#85] opened 2022-02-18 04:35 UTC
I'm seeing this weird behaviour that happens only on the Brave browser:

https://user-images.githubusercontent.com/69383359/154618225-ea7a7a7e-177d-4d27-9ae4-04ef3b5c4707.mov

I don't think I'm doing anything weird, just:

```js
import Head from "next/head";
import type { AppProps } from "next/app";
import { ThemeProvider } from "next-themes";
import { theme, darkTheme, globalStyles } from "stitches.config";
import { Page } from "@components/Page";

function MyApp({ Component, pageProps }: AppProps) {
  globalStyles();
  return (
    <ThemeProvider
      disableTransitionOnChange
      attribute="class"
      value={{ light: theme, dark: darkTheme }}
      defaultTheme="system"
    >
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </Head>
      <Page>
        <Component {...pageProps} />
      </Page>
    </ThemeProvider>
  );
}

export default MyApp;
```

If anyone has any idea what's going on it would be great !

**Comment by joeyvanlierop** [comment] 2022-02-21 23:12
Which version are you using? I noticed that v0.0.16 and newer have the flickering issue. I downgraded to v0.0.15 and the problem is no longer there.

**Comment by gr-qft** [comment] 2022-02-23 20:09
@joeyvanlierop Thanks for the help, I restarted the browser and the issue went away. Still, it would be interesting to understand the reason the flashing occurred, both in your case and in my case.

**Comment by kevinzunigacuellar** [comment] 2022-02-28 03:03
I have the same issue, I am using version 0.1.1 and chrome 98

**Comment by ivanandresdiaz** [comment] 2022-03-14 12:56
> I have the same issue, I am using version 0.1.1 and chrome 98. Downgrading to 0.0.15 worked btw 👍🏼

it worked for me, I was having a flashing with NEXT UI

**Comment by pacocoursey** [comment] 2022-05-05 00:22
Closing as duplicate to #90. Planning to release v0.2 soon that shouldn't have any flashing issues.

**Closed by pacocoursey** 2022-05-05 00:22 UTC
Labels: bug

**Comment by DenizUgur** [comment] 2023-01-11 20:55
This issue still persists on Firefox. Tested with the [demo](https://next-themes-example.vercel.app/) on the README.

**Comment by andrew-arkhipov** [comment] 2024-03-09 23:53
@pacocoursey Seeing this issue on `v0.2.1`. Users have complained that change from `dark` mode to `light` mode causes rapid flashing between the two, and the only fix is closing the browser.

Usage below:
```
<ThemeProvider enableSystem={false} attribute="class" disableTransitionOnChange>
```
