### ISSUE TITLE
Option to disable theme storage or use system value first

### ISSUE THREAD

**Issue by saheljalal** [pacocoursey/next-themes#140] opened 2022-09-21 06:12 UTC
I just thought I ran into a bug on [my app](https://eggsy.app) because it's night time and in Safari it kept showing light theme. But for some reason on Chrome it was dark.

After numerous hacks and changes, it dawned upon me that the browser was saving my last set theme value and used that on next relaunch.

But I may not necessarily want this behavior, i.e., when I launch my site I just want it to take the system value **always** first. Then if I toggle the theme, it's just persistent for the session my app is active until I close the tab or browser.

Any chance there is an option that supports disabling local storage or workaround to facilitate my desired behavior?

**Comment by pacocoursey** [comment] 2022-09-22 03:00
Sounds like a duplicate of #72 (using sessionStorage should achieve your desired behavior)

**Closed by pacocoursey** 2022-09-22 03:00 UTC
